---
title: "Homework 1"
author: "Author: Matthew J. Crossley"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
        collapsed: true
        smooth_scroll: true
    toc_depth: 3
    fig_caption: yes
    number_sections: false
    theme: cosmo
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reticulate)
use_python('/Users/mq20185996/miniconda3/bin/python')
```

## Learning objectives
* Demonstrate basic competence with `python`, `numpy`, and
`matplotlib`.

* Demonstrate basic understanding of how to use Euler's method
to approximate solutions to differential equations.

## 1
Use Euler's method to find an approximate solution to the
following differential equation:

$$
\frac{d}{dt}x(t) = \beta_0 + \beta_1 x(t) + \beta_2 x^2(t) + \beta_3 x^3(t)
$$

Plot your result with $t$ on the x-axis and $x(t)$ on the
y-axis (like the plot below). Try to Find values for the
time domain of your solution, the $\beta$s, and $x(0)$ that
lead to a solution like this:

```{python, echo=T, eval=T}
import numpy as np
import matplotlib.pyplot as plt

T = 100
tau = 0.1
t = np.arange(0, T, tau)
n = t.shape[0]

x = np.zeros(n)
x[0] = 2

beta_0 = .125
beta_1 = -.2
beta_2 = .09
beta_3 = -.01

for i in range(1, n):
  dt = t[i] - t[i-1]
  dxdt = beta_0 + beta_1 * x[i-1] + beta_2 * x[i-1]**2 + beta_3 * x[i-1]**3
  x[i] = x[i-1] + dxdt * dt

fig, ax = plt.subplots(1, 1, squeeze=False)
ax[0, 0].plot(t, x)
ax[0, 0].set_xlabel('t')
ax[0, 0].set_ylabel('x(t)')
plt.show()
```

## 2
Use Euler's method to find an approximate solution to the
following differential equation:

$$
\frac{d}{dt}x(t) = b - a x(t)
$$

a. Plot your result with $t$ on the x-axis and $x(t)$ on the
y-axis (like the plot below). Try to Find values for the
time domain of your solution, $a$, $b$, and $x(0)$ that lead
to a solution like this:

```{python, echo=T, eval=T}
import numpy as np
import matplotlib.pyplot as plt

T = 100
tau = 0.1
t = np.arange(0, T, tau)
n = t.shape[0]

x = np.zeros(n)
x[0] = 0.5
b = 0.1
a = 0.1

for i in range(1, n):
  dt = t[i] - t[i-1]
  dxdt = (b - a * x[i-1])
  x[i] = x[i-1] + dxdt * dt

fig, ax = plt.subplots(1, 1, squeeze=False)
ax[0, 0].plot(t, x)
ax[0, 0].set_xlabel('t')
ax[0, 0].set_ylabel('x(t)')
plt.show()
```

b. Add a reset condition to this dynamical system such that,
$x(t)$ is manually reset to zero whenever $x(t) > 1$.

$$
\frac{d}{dt}x(t) = b - a x(t) \\
\text{if } x(t) > 1, \text{then } x(t) \leftarrow 0
$$

Plot your result with $t$ on the x-axis and $x(t)$ on the
y-axis (like the plot below). Try to Find values for the
time domain of your solution, $a$, $b$, and $x(0)$ that lead
to a solution like this:

```{python, echo=T, eval=T}
import numpy as np
import matplotlib.pyplot as plt

T = 100
tau = 0.1
t = np.arange(0, T, tau)
n = t.shape[0]

x = np.zeros(n)
x[0] = 0.0
b = 0.1
a = 0.05

for i in range(1, n):
  dt = t[i] - t[i-1]
  dxdt = (b - a * x[i-1])
  x[i] = x[i-1] + dxdt * dt
  if x[i] > 1:
    x[i] = 0

fig, ax = plt.subplots(1, 1, squeeze=False)
ax[0, 0].plot(t, x)
ax[0, 0].set_xlabel('t')
ax[0, 0].set_ylabel('x(t)')
plt.show()
```

## 3
Use Euler's method to find an approximate solution to the
following differential equation:

$$
\frac{d}{dt}x(t) = b + a x^2(t)
$$

a. Plot your result with $t$ on the x-axis and $x(t)$ on the
y-axis (like the plot below). Try to Find values for the
time domain of your solution, $a$, $b$, and $x(0)$ that lead
to a solution like this:

```{python, echo=F, eval=T}
import numpy as np
import matplotlib.pyplot as plt

T = 100
tau = 0.1
t = np.arange(0, T, tau)
n = t.shape[0]

x = np.zeros(n)
x[0] = 0.0
b = 2e-2
a = 1e-2

for i in range(1, n):
  dt = t[i] - t[i-1]
  dxdt = (b + a * x[i-1]**2)
  x[i] = x[i-1] + dxdt * dt

fig, ax = plt.subplots(1, 1, squeeze=False)
ax[0, 0].plot(t, x)
ax[0, 0].set_xlabel('t')
ax[0, 0].set_ylabel('x(t)')
plt.show()
```

b. Add a reset condition to this dynamical system such that,
$x(t)$ is manually reset to zero whenever $x(t) > 1$.

$$
\frac{d}{dt}x(t) = b + a x^2(t) \\
\text{if } x(t) > 1, \text{then } x(t) \leftarrow 0
$$

Plot your result with $t$ on the x-axis and $x(t)$ on the
y-axis (like the plot below). Try to Find values for the
time domain of your solution, $a$, $b$, and $x(0)$ that lead
to a solution like this:

```{python, echo=T, eval=T}
import numpy as np
import matplotlib.pyplot as plt

T = 100
tau = 0.1
t = np.arange(0, T, tau)
n = t.shape[0]

x = np.zeros(n)
x[0] = 0.0
b = 3e-2
a = 1e-1

for i in range(1, n):
  dt = t[i] - t[i-1]
  dxdt = (b + a * x[i-1]**2)
  x[i] = x[i-1] + dxdt * dt
  if x[i] > 1:
    x[i] = 0

fig, ax = plt.subplots(1, 1, squeeze=False)
ax[0, 0].plot(t, x)
ax[0, 0].set_xlabel('t')
ax[0, 0].set_ylabel('x(t)')
plt.show()
```
